Run integration tests for both protocol 20 and 21

diff --git a/.github/workflows/soroban-rpc.yml b/.github/workflows/soroban-rpc.yml
--- a/.github/workflows/soroban-rpc.yml
+++ b/.github/workflows/soroban-rpc.yml
@@ -6,7 +6,7 @@ defaults:
 
 on:
   push:
-    branches: [main, release/**]
+    branches: [ main, release/** ]
   pull_request:
 
 jobs:
@@ -14,8 +14,8 @@ jobs:
     name: Unit tests
     strategy:
       matrix:
-        os: [ubuntu-20.04, ubuntu-22.04]
-        go: [1.22]
+        os: [ ubuntu-20.04, ubuntu-22.04 ]
+        go: [ 1.22 ]
     runs-on: ${{ matrix.os }}
     steps:
       - uses: actions/checkout@v3
@@ -105,13 +105,18 @@ jobs:
     continue-on-error: true
     strategy:
       matrix:
-        os: [ubuntu-20.04, ubuntu-22.04]
-        go: [1.22]
+        os: [ ubuntu-20.04, ubuntu-22.04 ]
+        go: [ 1.22 ]
+        protocol-version: [ 20, 21 ]
     runs-on: ${{ matrix.os }}
     env:
       SOROBAN_RPC_INTEGRATION_TESTS_ENABLED: true
+      SOROBAN_RPC_INTEGRATION_TESTS_CORE_MAX_SUPPORTED_PROTOCOL: ${{ matrix.protocol-version }}
       SOROBAN_RPC_INTEGRATION_TESTS_CAPTIVE_CORE_BIN: /usr/bin/stellar-core
-      CORE_DEBIAN_PKG_VERSION: 20.4.1-1807.b152dc51d.focal
+      PROTOCOL_20_CORE_DEBIAN_PKG_VERSION: 20.4.1-1807.b152dc51d.focal
+      PROTOCOL_20_CORE_DOCKER_IMG: stellar/unsafe-stellar-core:20.4.1-1807.b152dc51d.focal
+      PROTOCOL_21_CORE_DEBIAN_PKG_VERSION: 20.4.1-1807.b152dc51d.focal
+      PROTOCOL_21_CORE_DOCKER_IMG: stellar/unsafe-stellar-core:20.4.1-1807.b152dc51d.focal
     steps:
       - uses: actions/checkout@v3
         with:
@@ -120,9 +125,72 @@ jobs:
           # We need to full history for git-restore-mtime to know what modification dates to use.
           # Otherwise, the Go test cache will fail (due to the modification time of fixtures changing).
           fetch-depth: "0"
-      - uses: ./.github/actions/setup-integration-tests
+
+      - uses: ./.github/actions/setup-go
         with:
           go-version: ${{ matrix.go }}
+
+      - name: Pull and set Stellar Core image
+        shell: bash
+        run: |
+          docker pull "$PROTOCOL_${{ matrix.protocol-version }}_CORE_DOCKER_IMG"
+          echo HORIZON_INTEGRATION_TESTS_DOCKER_IMG="$PROTOCOL_${{ matrix.protocol-version }}_CORE_DOCKER_IMG" >> $GITHUB_ENV
+
+      - uses: stellar/actions/rust-cache@main
+
+      - name: Build soroban contract fixtures
+        shell: bash
+        run: |
+          rustup update
+          rustup target add wasm32-unknown-unknown
+          make build_rust
+          make build-test-wasms
+
+      - name: Install Captive Core
+        shell: bash
+        run: |
+          # Workaround for https://github.com/actions/virtual-environments/issues/5245,
+          # libc++1-8 won't be installed if another version is installed (but apt won't give you a helpful
+          # message about why the installation fails)
+          sudo apt-get remove -y libc++1-10 libc++abi1-10 || true
+
+          sudo wget -qO - https://apt.stellar.org/SDF.asc | APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=true sudo apt-key add -
+          sudo bash -c 'echo "deb https://apt.stellar.org focal unstable" > /etc/apt/sources.list.d/SDF-unstable.list'
+          sudo apt-get update && sudo apt-get install -y stellar-core="$PROTOCOL_${{ matrix.protocol-version }}_CORE_DEBIAN_PKG_VERSION"
+          echo "Using stellar core version $(stellar-core version)"
+
+      # Docker-compose's remote contexts on Ubuntu 20 started failing with an OpenSSL versioning error.
+      # See https://stackoverflow.com/questions/66579446/error-executing-docker-compose-building-webserver-unable-to-prepare-context-un
+      - name: Work around Docker Compose problem
+        shell: bash
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y ca-certificates curl gnupg
+
+          # Install docker apt repo
+          sudo install -m 0755 -d /etc/apt/keyrings
+          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
+          sudo chmod a+r /etc/apt/keyrings/docker.gpg
+          echo \
+            "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
+            "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
+            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+
+          # Install docker-compose v2 from apt repo
+          sudo apt-get update
+          sudo apt-get remove -y moby-compose
+          sudo apt-get install -y docker-compose-plugin
+
+          # add alias for docker compose
+          ln -f -s /usr/libexec/docker/cli-plugins/docker-compose /usr/local/bin/docker-compose
+
+          echo "Docker Compose Version:"
+          docker-compose version
+
+      - name: Build libpreflight
+        shell: bash
+        run: make build-libpreflight
+
       - name: Run Soroban RPC Integration Tests
         run: |
           make install_rust
